/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ObjectProgrammingLab1;

public class App {
    
    static Dog dog;
    static Cat cat;
    static Owner owner;

    public static void main(String[] args) {
        
        dog = new Dog(5, "Fafik", "Woof", "Teddy Bear");
        cat = new Cat(3, "Filemon", "Miau", "Ball");
        owner = new Owner(23, "Bartosz", "Dog");
        
        System.out.println("Dogs age: " + dog.age
                            + "\nDogs name: " + dog.name
                            + "\nDogs sound" + dog.sound
                            + "\nDogs favourite toy: " + dog.favouriteToy);
        
        System.out.println("Cats age: " + cat.age
                            + "\nCats name: " + cat.name
                            + "\nCats sound" + cat.sound
                            + "\nCats favourite toy: " + cat.favouriteToy);
        
        System.out.println("Owners age: " + owner.age
                            + "\nOwners name: " + owner.name
                            + "\nOwners favourite pet: " + owner.favouritePet);
        
        
    }
}
